import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import ToasterProvider from "@/utils/ToasterProvider";
import { UserContextProvider } from "@/context/UserContext";
import { ModalContextProvider } from "@/context/ModalContext";
import CommonModal from "@/components/modals/CommonModal";
import Header from "@/components/Header/Header";



const urbanistConfig = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanistConfig.variable}  
        antialiased`}
      >
        <ToasterProvider/>
        <ModalContextProvider>
        <UserContextProvider>
               <Header/>
          <CommonModal/>
        {children}
        </UserContextProvider>
        </ModalContextProvider>
      </body>
    </html>
  );
}
